name: Build UrbanNusaCyberr APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip git python3 python3-venv wget
          pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK Build Tools
        run: |
          # Siapkan direktori SDK
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          
          # Export environment variables
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          
          # Terima semua lisensi SDK
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --licenses || true
          
          # Instal semua komponen penting
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager \
            "platform-tools" "build-tools;36.0.1" "platforms;android-33"

      - name: Initialize buildozer environment
        run: |
          buildozer init || true
          # Pastikan buildozer.spec memiliki versi
          if ! grep -q "^version =" buildozer.spec; then
            echo "version = 1.0.0" >> buildozer.spec
          fi

      - name: Build APK
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: UrbanNusaCyberr-APK
          path: bin/*.apk
